#version should be changed with any pull requests
version: 2.3.{build}

clone_depth: 1
pull_requests:
  do_not_increment_build_number: true

init:
  - ps: |
      git config --global core.autocrlf input
      
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        $ver = $env:APPVEYOR_REPO_TAG_NAME
        if($ver.StartsWith("v") -eq $true) { $ver = $ver.Substring(1) }
        Update-AppveyorBuild -Version $ver
      }
      elseif([System.String]::IsNullOrEmpty($env:APPVEYOR_PULL_REQUEST_NUMBER) -eq $true) {
        $ver = $env:APPVEYOR_BUILD_VERSION
        $commit = $env:APPVEYOR_REPO_COMMIT.substring(0,7)
        Update-AppveyorBuild -Version "$ver-$commit"
      }

environment:
  matrix:
    - BUILD_TARGET: base
    - BUILD_TARGET: fsharp

build_script:
- cmd: dotnet build src/CommandLine/ -c Release --version-suffix %APPVEYOR_BUILD_VERSION% /p:BuildTarget=%BUILD_TARGET%

test_script: 
- cmd: dotnet test tests/CommandLine.Tests/ /p:BuildTarget=%BUILD_TARGET%

after_test:
- cmd: dotnet pack src/CommandLine/ -c Release --version-suffix %APPVEYOR_BUILD_VERSION% /p:BuildTarget=%BUILD_TARGET%

artifacts:
- path: 'src/CommandLine/bin/Release/*.nupkg'
  name: NugetPackages
  
on_failure:
- cmd: |
    tree /f /a >files.lst
    appveyor PushArtifact .\files.lst -DeploymentName "Failed Build File Listing"

deploy:
- provider: NuGet
  api_key:
    secure: +Zxb8M5W+UJV1yd9n8seu3PvH/hGNPEmgriGBnsSmtxjKPQAJ4+iL7tKAmfPHAuG
  artifact: 'NuGetPackages'
  on:
    branch: /master|v\d+\.\d+\.\d+[.*]/
    APPVEYOR_REPO_TAG: true

