#version should be changed with any pull requests
version: 2.2.{build}

clone_depth: 1
pull_requests:
  do_not_increment_build_number: true

#cache:
#- packages -> paket.dependencies
#- paket-files > paket.dependencies

init:
  - ps: |
      git config --global core.autocrlf input
      
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        $ver = $env:APPVEYOR_REPO_TAG_NAME
        if($ver.StartsWith("v") -eq $true) { $ver = $ver.Substring(1) }

        $env:APPVEYOR_BUILD_SEMVER = $ver
        
        if($ver.IndexOf("-") -gt -1) { 
            $verPreId = $ver.Substring($ver.IndexOf("-")+1)
            $ver = $ver.Substring(0,$ver.IndexOf("-"))
        } else {
            $verPreId = ""
        }

        if($verPreId -eq "") { $env:GITHUB_PRERELEASE="false" } else { $env:GITHUB_PRERELEASE="true" }

        $env:APPVEYOR_BUILD_VERSION = $ver
        $env:APPVEYOR_BUILD_VERSION_PREID = $verPreId
        Update-AppveyorBuild -Version $ver        
      }
      elseif([System.String]::IsNullOrEmpty($env:APPVEYOR_PULL_REQUEST_NUMBER) -eq $true) {
        $ver = $env:APPVEYOR_BUILD_VERSION
        $commit = $env:APPVEYOR_REPO_COMMIT.substring(0,7)
        $verInfo = "$ver-$commit"

        $env:APPVEYOR_BUILD_SEMVER = $verInfo
        Update-AppveyorBuild -Version $env:APPVEYOR_BUILD_SEMVER
      }

assembly_info:
  file: src\SharedAssemblyInfo.cs
  patch: true
  assembly_version: $(APPVEYOR_BUILD_VERSION)
  assembly_file_version: $(APPVEYOR_BUILD_VERSION)
  assembly_informational_version: $(APPVEYOR_BUILD_SEMVER)

build_script:
  - cmd: build.cmd

after_build:
- ps: |
    get-childitem build\* -include *.dll | foreach-object { "{0}`t{1}" -f $_.Name, [System.Diagnostics.FileVersionInfo]::GetVersionInfo($_).FileVersion }
    
    nuget pack CommandLine.nuspec -version "$env:APPVEYOR_BUILD_SEMVER"

test: off  #tests handled within FAKE

artifacts:
- path: '*.nupkg'
  name: NugetPackage
  
on_failure:
- cmd: |
    tree /f /a >files.lst
    appveyor PushArtifact .\files.lst -DeploymentName "Failed Build File Listing"

deploy:
- provider: NuGet
  api_key:
    secure: +Zxb8M5W+UJV1yd9n8seu3PvH/hGNPEmgriGBnsSmtxjKPQAJ4+iL7tKAmfPHAuG
  artifact: 'NuGetPackage'
  on:
    APPVEYOR_REPO_TAG: true
- provider: GitHub
  auth_token:
    secure: Km7E9dBin0YBa7/dFkZpyQ==
  artifact: NugetPackage
  prerelease: $(GITHUB_PRERELEASE)
  on:
    APPVEYOR_REPO_TAG: true


