#version should be changed with any pull requests
version: 2.2.0.{build}

clone_depth: 1
pull_requests:
  do_not_increment_build_number: true

cache:
- packages -> paket.dependencies

init:
  - git config --global core.autocrlf input
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
        Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }

build_script:
  - cmd: build.cmd

after_build:
- cmd: nuget pack CommandLine.nuspec -version %APPVEYOR_BUILD_VERSION%

test: off  #tests handled within FAKE build

artifacts:
- path: build/*.nupkg
  name: NugetPackage

deploy:
- provider: NuGet
  api_key:
    secure: +Zxb8M5W+UJV1yd9n8seu3PvH/hGNPEmgriGBnsSmtxjKPQAJ4+iL7tKAmfPHAuG
  artifact: 'NuGetPackage'
  on:
    branch: master
    APPVEYOR_REPO_TAG: true

